version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: logstash:7.6.2
    container_name: logstash
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    depends_on:
      - elasticsearch
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <your-mysql-root-password>
      MYSQL_DATABASE: <your-mysql-database>
      MYSQL_USER: <your-mysql-username>
      MYSQL_PASSWORD: <your-mysql-password>
    networks:
      - elknetwork

  springservice:
    image: springservice
    build: .
    container_name: springservice
    restart: always
    depends_on:
      - elasticsearch
      - mysql
    ports:
      - 8090:8090
    networks:
     - elknetwork

volumes:
  mysql:

networks:
  elknetwork:
    driver: bridge
